MAIOR_ENTRADA_POSSIVEL = 10
MAIOR_QUANTIDADE_CORES_POSSIVEL = 27
CORES = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S','T', 'U','V', 'W', 'X', 'Y', 'Z']
TAMANHO_ENTRADA = 3
MENOR_QUANTIDADE_CORES_POSSIVEL = 0
QUANT_GEMAS_MINIMA = 3
VAZIO = ' '