MAIOR_ENTRADA_POSSIVEL = 10
MAIOR_QUANTIDADE_CORES_POSSIVEL = 27
CORES = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S','T', 'U','V', 'W', 'X', 'Y', 'Z']
TAMANHO_ENTRADA = 3
MENOR_QUANTIDADE_CORES_POSSIVEL = 0
QUANT_GEMAS_MINIMA = 3
VAZIO = ' '
VAZIO_SEM_ESPACO = ''
SIM = 'sim'
NAO_HA_DISPONIVEIS = 'Não há dicas disponiveis'
AINDA_JOGADAS_DISPONIVEIS = 'Ainda há jogadas disponiveis nas casas'
NAO_FAZER_ESSE_MOVIMENTO = 'Voce não pode fazer esse movimento'
POWER_UP_5 = 5
POWER_UP_4 = 4
MARGEM_PECA_ATRAS = 2
MARGEM_PECA_FRENTE = 4
MARGEM_TABULEIRO = 6
NUMERO_DICA = 100